# Homework 4:

## Please put your name into the filename you submit.

### Note
For each question, there is the description and the coding block.  In the coding block, please finish the code with the hints provided.

You are free to use previous notes, google and all the other support.  I also encourage you to discuss with the other students in the class if anything is not clear.  Homework is for you to practice what we have learned during the class.

The homework will be due the end of the day before the next class.  For example, if I give you the homework on Thursday, then it will be due the end of the upcoming Monday.

## Q1 
#### 1.1 Write a function to take arbitrary number of numbers as input, return those numbers as a numpy vector.

In [6]:
# your code for Q1.1
import numpy as np
def func(*a):
    return np.array(a)

print(func(1,2,3,4,5))


[1 2 3 4 5]


#### 1.2 Can you improve the function to also print out the mean and sum of that vector at the same time.  So you want to return three different valuables at the same time, the numpy vector, the mean and the sum.

In [12]:
# your code for Q1.2
import numpy as np
def func(*a):
    arr = np.array(a)
    sum_arr = np.sum(np.array(a))
    mean_arr = np.mean(np.array(a))
    return arr, sum_arr, mean_arr

print(func(1,2,3,4,5))

(array([1, 2, 3, 4, 5]), 15, 3.0)


## Q2

#### Pleae follow the steps below:

- Generate a 3 by 5 array with constant value of 8
- Change the values of the zeroth column to 1.
- Add 10. to the values of the first row.
- Change its size to 5 by 3
- Print out the sum of the array

In [2]:
import numpy as np
# your code for Q2
# step 1
a = np.zeros((3,5))+8
print (a)

# step 2: 1st column
a[:,0:1]-=7
print(a)

# step 3: 1st row
a[0,:]+=10
print(a)

# 1st row, 2nd column
print(a[0,1]) 

# step 4
a = a.reshape(5, 3)
print(a)

# step 5
print(np.sum(a))

[[8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8.]]
[[1. 8. 8. 8. 8.]
 [1. 8. 8. 8. 8.]
 [1. 8. 8. 8. 8.]]
[[11. 18. 18. 18. 18.]
 [ 1.  8.  8.  8.  8.]
 [ 1.  8.  8.  8.  8.]]
18.0
[[11. 18. 18.]
 [18. 18.  1.]
 [ 8.  8.  8.]
 [ 8.  1.  8.]
 [ 8.  8.  8.]]
149.0


## Q3

#### For the dictionary below, can you save only the 'Year' and 'Total' values into a file like:
    Year   Total
    2015   91322
    2016   98146
    2017  103530
#### by using np.savetxt.  

You can copy the code of saving entire dictionary from the course notebook (5b) and modify based on that.


In [55]:
data={'Year':[2015,2016,2017],'Tempe':[51984,51869,51164],'Downtown':[10952,11737,11465],\
      'Polytechnic':[4078,4380,4809],'West':[3619,3663,4063],'Thunderbird':[416,297,327],'Total':[91322,98146,103530]}

In [56]:
type(data)

dict

In [84]:
all_data=[]
name=''
for key,value in data.items():
    name+=key+' '
    all_data.append(value)
print(name)
print(all_data)

name = np.array(name)
all_data=np.array(all_data).T
all_data

Year Tempe Downtown Polytechnic West Thunderbird Total 
[[2015, 2016, 2017], [51984, 51869, 51164], [10952, 11737, 11465], [4078, 4380, 4809], [3619, 3663, 4063], [416, 297, 327], [91322, 98146, 103530]]


array([[  2015,  51984,  10952,   4078,   3619,    416,  91322],
       [  2016,  51869,  11737,   4380,   3663,    297,  98146],
       [  2017,  51164,  11465,   4809,   4063,    327, 103530]])

In [88]:
arr = np.append([['Year', 'Tempe', 'Downtown', 'Polytechnic', 'West', 'Thunderbird', 'Total' ]], all_data, axis=0)
arr
# keep getting the ValueError here if using 'name'

array([['Year', 'Tempe', 'Downtown', 'Polytechnic', 'West',
        'Thunderbird', 'Total'],
       ['2015', '51984', '10952', '4078', '3619', '416', '91322'],
       ['2016', '51869', '11737', '4380', '3663', '297', '98146'],
       ['2017', '51164', '11465', '4809', '4063', '327', '103530']],
      dtype='<U21')

In [92]:
result = arr[: ['Year', 'Total']]

TypeError: slice indices must be integers or None or have an __index__ method

In [ ]:
np.savetxt('hw4_q3_data.dat', result)